mysite/books/urls.py
from django.urls import path
from . import views
# from . import models

app_name = 'books'

urlpatterns = [
    path('search/', views.search, name='search'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about_pages, name='about_pages'),
    path('publishers/', views.PulisherListView.as_view(), name='publisher_list'),
    path('publishers/<int:pub_id>', views.get_publisher, name='get_publisher'),
    path('hello/', views.generate_pdf),
    path('csv/', views.generate_csv)
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import current_datetime

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', current_datetime),
    path('books/', include('books.urls')),
    path('students/', include('students.urls')),
]

mysite/books/models.py
from django.db import models
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
imagePath = os.path.join(BASE_DIR, 'tmp')

# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=20)
    state_province = models.CharField(max_length=20)
    country = models.CharField(max_length=20)
    website = models.URLField()

    def __str__(self):
        return self.name
    # explicitly returning output with order_by "name"
    class Meta:
        ordering = ["name"]


class Author(models.Model):
    salutation = models.CharField(max_length=20)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField()
    headshot = models.ImageField(upload_to=imagePath)

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)


class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    publication_date = models.DateField()
    num_pages = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.title

mysite/books/forms.py
from django import forms

topic_choices = (
    ('general', 'General enquiry'),
    ('bug' 'Report a bug'),
    ('suggestion', 'Suggestion'),
)

class ContactForm(forms.Form):
    topic = forms.ChoiceField(choices=topic_choices)
    message = forms.CharField(widget=forms.Textarea())
    sender = forms.EmailField(required=False)

    # def clean_message(self):
    #     message = self.clean_data.get('message', '')
    #     num_words = len(message.spit())
    #     if num_words < 4:
    #         raise forms.ValidationError('Max. 4 chars!')
    #     return message

mysite/books/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.core.mail import send_mail
from django.db.models.query_utils import Q
from django.template import TemplateDoesNotExist
from django.views.generic import ListView
from books.models import Book, Publisher
from books.forms import ContactForm
from reportlab.pdfgen import canvas
import csv

def search (request):
    query = request.GET.get('q', '')
    if query:
        qset = (
            Q(title__contains=query) |
            Q(authors__first_name__contains=query) |
            Q(authors__last_name__contains=query)
        )
        results = Book.objects.filter(qset).distinct()
    else:
        results = []

    return render(request, 'books/search.html', {
        'results': results,
        'query': query
    })


def contact (request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            topic = form.cleaned_data['topic']
            message = form.cleaned_data['message']
            sender = form.cleaned_data.get('sender', 'noreply@example.com')
            send_mail(
                'Feedback from your site Mysite, topic: ' + topic,
                message, sender,
                ['admin@example.com']
            )
            print(topic + '--' + message + '--' + sender)
            return HttpResponseRedirect('<html><body>Thanks</body><html>')
    else:
        form = ContactForm()
    return render(request, 'books/contact.html', { 'form': form })


def about_pages(request):
    try:
        return render(request, 'books/about.html')
    except TemplateDoesNotExist:
        raise Http404()


class PulisherListView(ListView):
    model = Publisher
    context_object_name: str = 'pub_list'

def get_publisher(request, pub_id):
    publisher = get_object_or_404(Publisher, pk=pub_id)
    books = Book.objects.filter(publisher_id=publisher.id)
    return render(request, 'books/publisher_detail.html', {'publisher': publisher, 'books': books})


def generate_pdf (request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename=hello.pdf'

    p = canvas.Canvas(response)
    p.drawString(100, 100, "Hello World.")
    p.showPage()
    p.save()
    return response


UNRULY_PASSENGERS = [146,184,235,200,226,251,299,273,281,304,203]
def generate_csv (request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachement; filename=passenger.csv'

    writer = csv.writer(response)
    writer.writerow(['Year', 'No of Passengers'])
    for (year, num) in zip(range(1995, 2006), UNRULY_PASSENGERS):
        writer.writerow([year, num])
    
    return response

mysite/templates/books/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact us</title>
</head>
<body>
    <div class="container">
        <h3>Contact us</h3>
        <form action="." method="post">
            {% csrf_token %}
            <table>
                <tr>
                    <th><label for="id_topic">Topic:</label></th>
                    <td>
                        <select name="topic" id="id_topic">
                            <option value="general">General enquiry</option>
                            <option value="bug">Bug report</option>
                            <option value="suggestion">Suggestion</option>
                        </select>
                    </td>
                    </tr>
                    <tr>
                        <th><label for="id_message">Message:</label></th>
                        <td><input type="text" name="message" id="id_message" /></td>
                    </tr>
                    <tr>
                        <th><label for="id_sender">Sender:</label></th>
                        <td><input type="text" name="sender" id="id_sender" /></td>
                    </tr>
            </table>
            <p><input type="submit" value="Submit"></p>
        </form>
    </div>
</body>
</html>

mysite/templates/books/publisher_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Publisher Detail</title>
</head>
<body>
    <div class="container">
    <h2>Publisher Detail</h2>

    <h3>{{ publisher.name }}</h3>
    <p><strong>Website:</strong> {{publisher.website}}</p>
    <p><strong>Address:</strong> {{publisher.address}}</p>
    <p><strong>State/Province:</strong> {{publisher.state_province}}</p>
    <p><strong>Country:</strong> {{publisher.country}}</p>
    
    <label><strong>Books published</strong></label>
    {% if books %}
    {% for book in books %}
    <ul>
        <li>{{ book.title }}</li>
    </ul>
    {% endfor %}
    {% else %}
    <p>No books published yet</p>
    {% endif %}
    </div>
    <footer>
        <a href="{% url 'books:publisher_list' %}">Go back</a>
    </footer>
</body>
</html>

mysite/templates/books/publisher_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Publisher lists</title>
</head>
<body>
    <div class="container">
    <h2>Publishers</h2>
    <ul>
        {% for publisher in pub_list %}
        <li><a href="{% url 'books:get_publisher' publisher.id %}">{{ publisher.name }}</a> ({{ publisher.website }})</li>
        {% endfor %}
    </ul>
    </div>
</body>
</html>

mysite/templates/books/search.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search books</title>
    <style>
        .container {
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            text-align: center;
            font-size: 20px;
            background-color: hsl(33, 100%, 88%);
            padding-top: 20px;
            padding-bottom: 20px;
        }

        .btn {
            background-color: lightgreen;
            border-color: green;
            border-radius: 2px;
        }

        li {
            list-style: none;
        }
    </style>
</head>

<body>
    <div class="container">
        <h3>Search for books, authors</h3>
        <form action="." method="GET">
            <input type="text" name="q" value="{{ query|escape }}" placeholder="enter book or author">
            <input class="btn" type="submit" value="Search">
        </form>
        {% if query %}
        <h4>Results for "{{ query|escape }}" ({{ results.count }} result{{ results | pluralize }})</h4>
        {% if results %}
        <ul>
            {% for book in results %}
            <li>{{ book }}</l1>
            {% endfor %}
        </ul>
        {% else %}
        <p>No books found!</p>
        {% endif %}
        {% endif %}
    </div>
</body>

</html>