mysite/books/urls.py
from django.urls import path
from . import views
# from . import models

app_name = 'books'

urlpatterns = [
    path('search/', views.search, name='search'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about_pages, name='about_pages'),
    path('publishers/', views.PulisherListView.as_view(), name='publisher_list'),
    path('publishers/<int:pub_id>', views.get_publisher, name='get_publisher'),
    path('hello/', views.generate_pdf),
    path('csv/', views.generate_csv)
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import current_datetime

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', current_datetime),
    path('books/', include('books.urls')),
    path('students/', include('students.urls')),
]

mysite/students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
    path('hello/', views.hello),
    path('list/', views.student_list.as_view(), name='student_list'),
    path('marksheet/<int:id>', views.marksheet, name='marksheet'),
    path('marksheet/<int:id>', views.marksheet, name='get_marks'),
    path('page/', views.student_page, name='student_page')
]

mysite/students/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

grade_values = [
    ('10', '10'),
    ('11', '11'),
    ('12', '12'),
]

mark_validator = [
    MinValueValidator(0), MaxValueValidator(100)
]
help_text = "Mark should be between 0 and 100"

subject_list = [
    ('English', 'English'),
    ('German', 'German'),
    ('Science', 'Science'),
    ('Social Studies', 'Social Studies'),
    ('Math', 'Math'),
    ('Ethics', 'Ethics'),
]

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=100)
    grade = models.CharField(max_length=2, choices=grade_values)
    dob = models.DateField('Date of Birth')

    def __str__(self) -> str:
        return self.name


class Marksheet(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    subject = models.CharField(max_length=30, choices=subject_list)
    mark = models.PositiveIntegerField(
        validators=mark_validator, help_text=help_text, default=0
    )

    def __str__(self) -> str:
        return self.subject
            

mysite/students/views.py
import json
from django.shortcuts import render, HttpResponse, get_object_or_404
from django.http import Http404
from django.views.generic import ListView
from django.db.models import Sum, Avg
from django.db.models.functions import Round
from .models import Student, Marksheet

# Marksheet.objects.filter(student_id=1).values('student_id').annotate(total=Sum('mark'))
# Marksheet.objects.filter(student_id=1).values('student_id').annotate(avg=Round(Avg('mark')))

# Create your views here.
def hello(request):
    return HttpResponse('Hello students')

def marksheet(request, id):
    try:
        student = get_object_or_404(Student, pk=id)
        mark = Marksheet.objects.filter(student_id = student.id)
        t = Marksheet.objects.filter(student_id = student.id).values('student_id').annotate(total=Sum('mark'))
        a = Marksheet.objects.filter(student_id = student.id).values('student_id').annotate(avg=Round(Avg(('mark'))))
        
        # mark_list = [{'subject': mark[i]} for i in range(0, mark.count())]

        total = t[0]['total']
        avg = a[0]['avg']
        
        # return HttpResponse(json.dumps({'total': total, 'avg': avg}), content_type="application/json")
        return render(request, 'students/student_mark.html', {'total': total, 'avg': avg, 'student': student, 'marks': mark})

    except (IndexError):
        return render(request, 'students/student_mark.html', {'student': student, 'message': 'Marksheet not available'})



class student_list(ListView):
    model = Student
    context_object_name = 'student_list'

def student_page(request):
    try:
        student = Student.objects.all().order_by('-grade', 'name')
        mark_list = [
            {
                'student': student[i], 
                'mark_details': Marksheet.objects.filter(student_id= student[i].id),
                'total': Marksheet.objects.filter(student_id = student[i].id).values('student_id').annotate(total=Sum('mark'))
            }
            for i in range(0, student.count())
        ]
        # print(mark_list)
        
        return render(request, 'students/student_page.html', {'mark_list': mark_list})
    except:
        pass

mysite/templates/students/student_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Students list</title>
</head>
<body>
    <div class="container">
    <h2 class="h2-l">Students</h2>
        {% for student in student_list %}
        <li class="nobullet"><a class="student-link" href="{% url 'students:marksheet' student.id %}">{{ student.name }}</a> (Grade: {{ student.grade }})</li>
        {% endfor %}
        <p><a href="{% url 'students:student_page' %}">Tableview</a></p>
    </div>
</body>
</html>

mysite/templates/students/student_mark.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Student Marksheet</title>
</head>
<body>
    <div class="container">
        <h2>{{ student }}'s Marksheet</h2>
        <p>Grade : {{ student.grade }}</p>
        <p>DOB : {{ student.dob }}</p>
        {% if message %}
            <p><strong>{{ message }}</strong></p>
        {% else %}
        <table>
            <thead class="tbl-header"> 
                <td>Subject</td>
                <td>Mark</td>
            </thead>
            <tbody>
                {% for mark in marks %}
                <tr>
                    <td>{{ mark.subject }}</td>
                    <td>{{ mark.mark }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <p>Total: {{ total }} / 600 | Result: {% if total >= 530 %} <label style="color: hsl(120, 100%, 25%, 60%);">Pass</label> {% else %} <label style="color: red">Fail</label> {% endif %}</p>
        <p>Average: {{ avg }} (average of {{ marks.count }} subject{{ marks | pluralize }})</p>
        {% endif %}
        <p><a href="{% url 'students:student_list' %}">Listview</a> | <a href="{% url 'students:student_page' %}">Tableview</a></p>
    </div>
</body>
</html>

mysite/templates/students/student_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Student details</title>
</head>
<body>
    <div class="container">
    <h2 class="h2-l">Student details</h2>
        <table>
            <thead class="tbl-header">
                <td>Name</td>
                <td>Grade</td>
                <td>DOB</td>
                <td>English</td>
                <td>German</td>
                <td>Science</td>
                <td>Social Studies</td>
                <td>Math</td>
                <td>Ethics</td>
                <td>Total</td>
                <td>Result</td>
            </thead>
            <tbody>
                {% for m in mark_list %}
                    <tr>
                        <td class="std-cell"><a class="student-link" href="{% url 'students:marksheet' m.student.id %}">{{ m.student.name }}</a></td>
                        <td class="std-cell">{{ m.student.grade }}</td>
                        <td class="std-cell">{{ m.student.dob }}</td>
                        {% for d in m.mark_details %}
                        <td>{{ d.mark }}</td>
                        {% endfor %}
                        {% for t in m.total %}
                        <td>{{ t.total }}</td>
                        {% endfor %}
                        {% for t in m.total %}
                        {% if t.total >= 530 %}
                        <td style="background-color: hsl(120, 73%, 75%, 75%);">Pass</td>
                        {% else %}
                        <td style="background-color: hsl(0, 100%, 50%, 50%);">Fail</td>
                        {% endif %}
                        {% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <p><a href="{% url 'students:student_list' %}">Listview</a></p>
    </div>
</body>
</html>